Add `binary_sensor`
oxan/esphome-stream-server pull request #15
Opened 2022-01-18 22:36 UTC by joshuaspence

Fixes #8

2022-01-19 08:30 UTC, oxan requested changes

2022-01-19 08:30 UTC, oxan commented on README.md
> +	  stream_server: ss
This code block needs to be terminated.

2022-01-19 08:30 UTC, oxan commented on components/stream_server/binary_sensor.py
> +class_ = ns.class_("BinarySensor", binary_sensor.BinarySensor, cg.Component)
This doesn't make sense (you're redefining the `esphome::esphome::BinarySensor` class to inherit from itself and `esphome::Component`), just use `binary_sensor.BinarySensor` instead of `class_`.

2022-01-19 08:30 UTC, oxan commented on components/stream_server/stream_server.h
> +    void register_connection_sensor(esphome::binary_sensor::BinarySensor *connection_sensor) {this->connection_sensor_ = connection_sensor; }
I prefer to add a separate class, `StreamServerBinarySensor` or something like that, that inherits from `BinarySensor` and has the `StreamServer` itself as a member. That allows us to decouple from the `binary_sensor` integration and remove it from autoload, so that it's only loaded and compiled when in use.

2022-01-19 08:30 UTC, oxan commented on components/stream_server/binary_sensor.py
> +    cg.add(ss.register_connection_sensor(var))
For consistency with `__init__.py`, please indent this file with tabs.

2022-01-19 22:33 UTC, joshuaspence commented on components/stream_server/stream_server.h
> +    void register_connection_sensor(esphome::binary_sensor::BinarySensor *connection_sensor) {this->connection_sensor_ = connection_sensor; }
I was thinking that but thought I'd keep it simple. I agree with your reasoning and will make the change.

2022-01-20 21:37 UTC, oxan approved these changes

2022-01-30 23:28 UTC, joshuaspence commented
@oxan Anything else needed before we can merge this?

2022-05-15 22:54 UTC, ruimarinho commented
Looks good!

2022-07-02 04:32 UTC, joshuaspence commented
@oxan are you still interested in this change?

2022-12-09 17:57 UTC, akalagov commented
This is a much needed feature!

2023-02-03 01:01 UTC, oxan commented
Hi! Sorry for the silence, I've neglected this project quite a bit over the last year. 

Tonight I've finally finished the major refactoring to port to ESPHome's socket abstractions, which is in PR #25. I've also squashed this PR into that branch, albeit somewhat refactored to not create the binary sensor as a separate component. I want to do some more testing over the weekend, but if that succeeds I'll merge that one into master and we're finally done with this. Thanks for your contribution in any case!

2023-02-07 21:17 UTC, oxan commented
The functionality from this PR has been merged with #25.

2023-02-07 21:17 UTC, closed without merging